name: CI and automatic releases
on:
  push:
    branches-ignore: [gh-pages]
jobs:
  ci:
    name: "Run static checks and tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Cache Grade dependencies
        uses: actions/cache@v1
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build
#      - name: Run tests on physical and virtual devices
#        uses: asadmansr/Firebase-Test-Lab-Action@v1.0
#        with:
#          arg-spec: 'app/firebase-test-lab.yml:spec'
#        env:
#          SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
